on:
  push:
    branches:
      - main
  pull_request: {}
name: CI
jobs:
  janitorial:
    name: janitorial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          toolchain: stable
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        target:
          - arm-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
        feature_flags:
          - ''
          - '--features std'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --release --target=${{ matrix.target }} ${{ matrix.feature_flags }}
